config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # read
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: 'task' # here we set as task
  # this ensures that we can make the link_to task['title'] and task_path work
  # which takes the path tasks/task['id']
  # create
  post 'tasks', to: 'tasks#create'
  # edit
  # step1: get the html form
  # step2: patch the params to save the task
  # remember, as we are editing a single task instance
  # we need to specify the id
  get 'tasks/:id/edit', to: 'tasks#edit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    # we need to find the task to show it by id
    @task = Task.find(params[:id])
    # raise
    # to see what is inside the value of params, which id is
  end

  def new
    @task = Task.new
    # then in the respective view, we use the helper form_for to make the form
  end

  def create
    @task = Task.new(tasks_params)
    @task.save

    # this takes us to the task show page
    redirect_to task_path(@task)
  end

  def edit
    # need to find the task to show it by id again
    @task = Task.find(params[:id])
  end

  private

  # we need strong params to save the data in the db
  # this tasks_params method is needed to bypass the forbidden attributes error
  # because it is a security method to prevent users from updating the form
  # and use malicious code in the params
  # we can replace params[:task] in create, etc
  # with this method call to bypass the security
  def tasks_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%# <%= form_for(task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.text_field :completed %>
  <%= t.submit %>
<% end %> %>

app/views/tasks/edit.html.erb
<h1>EDIT TASK FORM</h1>

<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.text_field :completed %>
  <%= t.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>List of all tasks!!!</h1>
<ul>
  <% @tasks.each do |task| %>
  <li><%= link_to task['title'], task_path(task['id']) %></li>
  <% end %>
</ul>

<%= link_to 'add a task', tasks_new_path %>

app/views/tasks/new.html.erb
<h1>TASK FORM</h1>

<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.text_field :completed %>
  <%= t.submit %>
<% end %>

app/views/tasks/show.html.erb
<h3><%= @task.title %></h3>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<%= link_to 'return to tasks', tasks_path %>